version: "1"
rules:
  - base: upstream_master
    upstream: cdhigh:master
    mergeMethod: hardreset
  - base: master
    upstream: cdhigh:master
    mergeMethod: hardreset
  - base: dev
    upstream: master
label: ":arrow_heading_down: pull"
